name: "ci"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  units-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run lint
      - run: npm run test -- --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  integration:
    needs: units-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Generate distributed action
        run: npm run compile
      - name: Test generated action
        uses: ./
        with:
          milliseconds: 1000